### ISSUE TITLE
Nano bots = long save time, plus huge save file. 

### ISSUE THREAD

**Issue by cjmwid** [Nexela/Nanobots#61]
Currently have a mod pack going with bobs + angels. It's taking a while to save the map over about 40 secs plus. According to one of the factorio devs that viewed the file. This mod is saving over 100mb in the global table. That's causing the saves to take a long time.

**Comment by Nexela** [comment]
This is on my list of things to fix. I believe it is related to the robointerface (are you using any?)
In the meantime running this command should clear everything up.
/c remote.call("nanobots", "reset_mod", true)

**Comment by cjmwid** [comment]
I can run the command when I get home and give ya results. Do you wabt the mod pack and save? Before and after?

**Comment by Nexela** [comment]
Yes please

**Comment by cgc007** [comment]
I have another save file that I just narrowed it down to.
If I remove only nanobots, the save works as per normal.
If I run the command, it works per normal.

Files are located here. 
https://www.dropbox.com/sh/1ty7dykcixuy9wa/AABFgSTDejBtG57mFHulJXEaa?dl=0

**Comment by msu320** [comment]
looks like global.cell_queue is getting oversized:
![cell_queue](https://user-images.githubusercontent.com/17893039/33144874-89bc987c-cf8c-11e7-8c26-07a2ff5d7a36.png)

**Comment by chrisgbk** [comment]
> looks like global.cell_queue is getting oversized:
> 
> EDIT: found this after investigating a save found here:
> https://www.reddit.com/r/factorio/comments/7epusy/2_minutes_to_save_26mb/

Can also get a nice human-readable format with `/c remote.call("nanobots","print_global")` which will dump to `script-output/Nanobots/global.lua`. It's about 180MB and just shy of 8 million lines, so it takes a while to run.


Since I looked around the code:

`if not cell.mobile and cell.construction_radius > 0 and not (hash and hash[param_table.action]) then`

shouldn't this be:

`if not cell.mobile and cell.construction_radius > 0 and not (hash and hash[param_name]) then`

since _hash in hash_queue stores names, not actions: `hash = param_name,`. Alternatively maybe `hash = param_table.action,` is the solution; I haven't fully worked out how everything works or what everything does, but it seems like there is some discrepancy between what is checked and what is stored. I think this is what is resulting in the huge amount of data being saved.

     _hash = {
          [138946] = {
            count = 727,
            ["nano-signal-catch-fish"] = "nano-signal-catch-fish",
            ["nano-signal-chop-trees"] = "nano-signal-chop-trees",
            ["nano-signal-deconstruct-finished-miners"] = "nano-signal-deconstruct-finished-miners",
            ["nano-signal-item-on-ground"] = "nano-signal-item-on-ground"
          },

    ...

    [22377623] = {
      [1] = {
        action = "mark_items_or_trees",
        entity = {
          __self = "userdata: 0x0000025f01b24bc0"
        },
        find_type = "item-entity",
        hash = 138946,
        logistic_cell = {
          __self = "userdata: 0x0000025f01b5f6e0"
        },
        logistic_network = nil,
        name = "nano-signal-item-on-ground",
        position = {
          x = -81,
          y = 48
        },
        unit_number = 138946,
        value = 1
      }
    },

**Comment by Nexela** [comment]
This should be fixed in the latest release,  170fc14

Also added some commands to help clean up if it bloats again.  Please report any issues here!
/nanobots reset cell_queue
/nanobots reset nano_queue
/nanobots reset mod
